<?php

namespace Database\Seeders;

use App\Models\Admin\RoleManagement\Permission;
use Illuminate\Database\Seeder;

class PermissionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
//        Permission::factory()
//            ->count(5)
//            ->create();

        Permission::insert([
            [
                'id' => 1,
                'permission_category_id'  => 1,
                'title'  => 'Super Admin Dashboard',
                'slug'  => 'super-admin-dashboard',
                'status'    => 1,
                'is_default'    => 1,
            ],
            [
                'id' => 2,
                'permission_category_id'  => 1,
                'title'  => 'Admin Dashboard',
                'slug'  => 'admin-dashboard',
                'status'    => 1,
                'is_default'    => 1,
            ],
            [
                'id' => 3,
                'permission_category_id'  => 1,
                'title'  => 'Moderator Dashboard',
                'slug'  => 'moderator-dashboard',
                'status'    => 1,
                'is_default'    => 1,
            ],
            [
                'id' => 4,
                'permission_category_id'  => 1,
                'title'  => 'Editor Dashboard',
                'slug'  => 'editor-dashboard',
                'status'    => 1,
                'is_default'    => 1,
            ],
            [
                'id' => 5,
                'permission_category_id'  => 1,
                'title'  => 'Stuff Dashboard',
                'slug'  => 'stuff-dashboard',
                'status'    => 1,
                'is_default'    => 1,
            ],
            [
                'id' => 6,
                'permission_category_id'  => 1,
                'title'  => 'Normal User Dashboard',
                'slug'  => 'normal-user-dashboard',
                'status'    => 1,
                'is_default'    => 1,
            ],
            [
                'id' => 7,
                'permission_category_id'  => 2,
                'title'  => 'Manage Permission Category',
                'slug'  => 'manage-permission-category',
                'status'    => 1,
                'is_default'    => 1,
            ],
            [
                'id' => 8,
                'permission_category_id'  => 2,
                'title'  => 'Create Permission Category',
                'slug'  => 'create-permission-category',
                'status'    => 1,
                'is_default'    => 1,
            ],
            [
                'id' => 9,
                'permission_category_id'  => 2,
                'title'  => 'Store Permission Category',
                'slug'  => 'store-permission-category',
                'status'    => 1,
                'is_default'    => 1,
            ],
            [
                'id' => 10,
                'permission_category_id'  => 2,
                'title'  => 'Edit Permission Category ',
                'slug'  => 'edit-permission-category',
                'status'    => 1,
                'is_default'    => 1,
            ],
            [
                'id' => 11,
                'permission_category_id'  => 2,
                'title'  => 'Update Permission Category',
                'slug'  => 'update-permission-category',
                'status'    => 1,
                'is_default'    => 1,
            ],
            [
                'id' => 12,
                'permission_category_id'  => 2,
                'title'  => 'Show Permission Category',
                'slug'  => 'show-permission-category',
                'status'    => 1,
                'is_default'    => 1,
            ],
            [
                'id' => 13,
                'permission_category_id'  => 2,
                'title'  => 'Delete Permission Category',
                'slug'  => 'delete-permission-category',
                'status'    => 1,
                'is_default'    => 1,
            ],

            //      ================ Permission ===========
            [
                'id' => 14,
                'permission_category_id'  => 2,
                'title'         => 'Manage Permission',
                'slug'          => 'manage-permission',
                'status'        => 1,
                'is_default'    => 1,
            ],
            [
                'id' => 15,
                'permission_category_id'  => 2,
                'title'         => 'Create Permission',
                'slug'          => 'create-permission',
                'status'        => 1,
                'is_default'    => 1,
            ],
            [
                'id' => 16,
                'permission_category_id'  => 2,
                'title'         => 'Store Permission ',
                'slug'          => 'store-permission',
                'status'        => 1,
                'is_default'    => 1,
            ],
            [
                'id' => 17,
                'permission_category_id'  => 2,
                'title'         => 'Edit Permission',
                'slug'          => 'edit-permission',
                'status'        => 1,
                'is_default'    => 1,
            ],
            [
                'id' => 18,
                'permission_category_id'  => 2,
                'title'         => 'Update Permission',
                'slug'          => 'update-permission',
                'status'        => 1,
                'is_default'    => 1,
            ],
            [
                'id' => 19,
                'permission_category_id'  => 2,
                'title'         => 'Show Permission',
                'slug'          => 'show-permission',
                'status'        => 1,
                'is_default'    => 1,
            ],
            [
                'id' => 20,
                'permission_category_id'  => 2,
                'title'  => 'Delete Permission',
                'slug'  => 'delete-permission',
                'status'    => 1,
                'is_default'    => 1,
            ],

//      ================ Role ===========
            [
                'id' => 21,
                'permission_category_id'  => 3,
                'title'       => 'Manage Role',
                'slug'        => 'manage-role',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 22,
                'permission_category_id'  => 3,
                'title'      => 'Create Role',
                'slug'       => 'create-role',
                'status'     => 1,
                'is_default' => 1,
            ],
            [
                'id' => 23,
                'permission_category_id'  => 3,
                'title'         => 'Store Role ',
                'slug'          => 'store-role',
                'status'        => 1,
                'is_default'    => 1,
            ],
            [
                'id' => 24,
                'permission_category_id'  => 3,
                'title'         => 'Edit Role',
                'slug'          => 'edit-role',
                'status'        => 1,
                'is_default'    => 1,
            ],
            [
                'id' => 25,
                'permission_category_id'  => 3,
                'title'       => 'Update Role',
                'slug'        => 'update-role',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 26,
                'permission_category_id'  => 3,
                'title'       => 'Show Role',
                'slug'        => 'show-role',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 27,
                'permission_category_id'  => 3,
                'title'       => 'Delete Role',
                'slug'        => 'delete-role',
                'status'      => 1,
                'is_default'  => 1,
            ],
// ================ User Role =================
// ================ need to check again start =================
            [
                'id' => 28,
                'permission_category_id'  => 16,
                'title'       => 'Manage User',
                'slug'        => 'manage-user',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 29,
                'permission_category_id'  => 16,
                'title'       => 'Create User',
                'slug'        => 'create-user',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 30,
                'permission_category_id'  => 16,
                'title'       => 'Store User ',
                'slug'        => 'store-user',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 31,
                'permission_category_id'  => 16,
                'title'       => 'Edit User',
                'slug'        => 'edit-user',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 32,
                'permission_category_id'  => 16,
                'title'       => 'Update User',
                'slug'        => 'update-user',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 33,
                'permission_category_id'  => 16,
                'title'       => 'Show User',
                'slug'        => 'show-user',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 34,
                'permission_category_id'  => 16,
                'title'       => 'Delete User',
                'slug'        => 'delete-user',
                'status'      => 1,
                'is_default'  => 1,
            ],

// ================ Blog Category =================
            [
                'id' => 162,
                'permission_category_id'  => 10,
                'title'       => 'Manage Blog Category',
                'slug'        => 'manage-blog-category',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 163,
                'permission_category_id'  => 10,
                'title'       => 'Create Blog Category',
                'slug'        => 'create-blog-category',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 164,
                'permission_category_id'  => 10,
                'title'       => 'Store Blog Category',
                'slug'        => 'store-blog-category',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 165,
                'permission_category_id'  => 10,
                'title'       => 'Edit Blog Category',
                'slug'        => 'edit-blog-category',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 166,
                'permission_category_id'  => 10,
                'title'       => 'Update Blog Category',
                'slug'        => 'update-blog-category',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 167,
                'permission_category_id'  => 10,
                'title'       => 'Show Blog Category',
                'slug'        => 'show-blog-category',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 168,
                'permission_category_id'  => 10,
                'title'       => 'Delete Blog Category',
                'slug'        => 'delete-blog-category',
                'status'      => 1,
                'is_default'  => 1,
            ],

// ================ Blog =================
            [
                'id' => 169,
                'permission_category_id'  => 10,
                'title'       => 'Manage Blog',
                'slug'        => 'manage-blog',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 170,
                'permission_category_id'  => 10,
                'title'       => 'Create Blog',
                'slug'        => 'create-blog',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 171,
                'permission_category_id'  => 10,
                'title'       => 'Store Blog',
                'slug'        => 'store-blog',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 172,
                'permission_category_id'  => 10,
                'title'       => 'Edit Blog',
                'slug'        => 'edit-blog',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 173,
                'permission_category_id'  => 10,
                'title'       => 'Update Blog',
                'slug'        => 'update-blog',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 174,
                'permission_category_id'  => 10,
                'title'       => 'Show Blog',
                'slug'        => 'show-blog',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 175,
                'permission_category_id'  => 10,
                'title'       => 'Delete Blog',
                'slug'        => 'delete-blog',
                'status'      => 1,
                'is_default'  => 1,
            ],

// ================  Notice Category =================
            [
                'id' => 210,
                'permission_category_id'  => 13,
                'title'       => 'Manage Notice Category',
                'slug'        => 'manage-notice-category',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 211,
                'permission_category_id'  => 13,
                'title'       => 'Create Notice Category',
                'slug'        => 'create-notice-category',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 212,
                'permission_category_id'  => 13,
                'title'       => 'Store Notice Category',
                'slug'        => 'store-notice-category',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 213,
                'permission_category_id'  => 13,
                'title'       => 'Edit Notice Category',
                'slug'        => 'edit-notice-category',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 214,
                'permission_category_id'  => 13,
                'title'       => 'Update Notice Category',
                'slug'        => 'update-notice-category',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 215,
                'permission_category_id'  => 13,
                'title'       => 'Show Notice Category',
                'slug'        => 'show-notice-category',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 216,
                'permission_category_id'  => 13,
                'title'       => 'Add Sub Category To Notice Category',
                'slug'        => 'add-sub-cat-to-notice-category',
                'status'      => 1,
                'is_default'  => 1,
            ],

// ================  Notice =================
            [
                'id' => 217,
                'permission_category_id'  => 13,
                'title'       => 'Manage Notice',
                'slug'        => 'manage-notice',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 218,
                'permission_category_id'  => 13,
                'title'       => 'Create Notice',
                'slug'        => 'create-notice',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 219,
                'permission_category_id'  => 13,
                'title'       => 'Store Notice',
                'slug'        => 'store-notice',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 220,
                'permission_category_id'  => 13,
                'title'       => 'Edit Notice',
                'slug'        => 'edit-notice',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 221,
                'permission_category_id'  => 13,
                'title'       => 'Update Notice',
                'slug'        => 'update-notice',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 222,
                'permission_category_id'  => 13,
                'title'       => 'Show Notice',
                'slug'        => 'show-notice',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 223,
                'permission_category_id'  => 13,
                'title'       => 'Delete Notice',
                'slug'        => 'delete-notice',
                'status'      => 1,
                'is_default'  => 1,
            ],

// ================ User & User Profile =================
            [
                'id' => 278,
                'permission_category_id'  => 16,
                'title'       => 'View User Profile',
                'slug'        => 'view-user-profile',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 279,
                'permission_category_id'  => 16,
                'title'       => 'User Change Password',
                'slug'        => 'admin-form-user-change-password',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 280,
                'permission_category_id'  => 16,
                'title'       => 'All Users Page',
                'slug'        => 'all-users-page',
                'status'      => 1,
                'is_default'  => 1,
            ],


// ================ Page =================
            [
                'id' => 288,
                'permission_category_id'  => 18,
                'title'       => 'Manage Page',
                'slug'        => 'manage-page',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 289,
                'permission_category_id'  => 18,
                'title'       => 'Create Page',
                'slug'        => 'create-page',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 290,
                'permission_category_id'  => 18,
                'title'       => 'Store Page',
                'slug'        => 'store-page',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 291,
                'permission_category_id'  => 18,
                'title'       => 'Edit Page',
                'slug'        => 'edit-page',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 292,
                'permission_category_id'  => 18,
                'title'       => 'Update Page',
                'slug'        => 'update-page',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 293,
                'permission_category_id'  => 18,
                'title'       => 'Show Page',
                'slug'        => 'show-page',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 294,
                'permission_category_id'  => 18,
                'title'       => 'Delete Page',
                'slug'        => 'delete-page',
                'status'      => 1,
                'is_default'  => 1,
            ],
// ================ Contact =================
            [
                'id' => 295,
                'permission_category_id'  => 19,
                'title'       => 'Manage Contact',
                'slug'        => 'manage-contact',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 296,
                'permission_category_id'  => 19,
                'title'       => 'Create Contact',
                'slug'        => 'create-contact',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 297,
                'permission_category_id'  => 19,
                'title'       => 'Store Contact',
                'slug'        => 'store-contact',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 298,
                'permission_category_id'  => 19,
                'title'       => 'Edit Contact',
                'slug'        => 'edit-contact',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 299,
                'permission_category_id'  => 19,
                'title'       => 'Update Contact',
                'slug'        => 'update-contact',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 300,
                'permission_category_id'  => 19,
                'title'       => 'Show Contact',
                'slug'        => 'show-contact',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 301,
                'permission_category_id'  => 19,
                'title'       => 'Delete Contact',
                'slug'        => 'delete-contact',
                'status'      => 1,
                'is_default'  => 1,
            ],
// ================ Information =================
            [
                'id' => 319,
                'permission_category_id'  => 22,
                'title'       => 'Manage Information',
                'slug'        => 'manage-information',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 320,
                'permission_category_id'  => 22,
                'title'       => 'Create Information',
                'slug'        => 'create-information',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 321,
                'permission_category_id'  => 22,
                'title'       => 'Store Information',
                'slug'        => 'store-information',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 322,
                'permission_category_id'  => 22,
                'title'       => 'Edit Information',
                'slug'        => 'edit-information',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 323,
                'permission_category_id'  => 22,
                'title'       => 'Update Information',
                'slug'        => 'update-information',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 324,
                'permission_category_id'  => 22,
                'title'       => 'Show Information',
                'slug'        => 'show-information',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 325,
                'permission_category_id'  => 22,
                'title'       => 'Delete Information',
                'slug'        => 'delete-information',
                'status'      => 1,
                'is_default'  => 1,
            ],

// ================ Notification =================
            [
                'id' => 326,
                'permission_category_id'  => 24,
                'title'       => 'Manage Notification',
                'slug'        => 'manage-notification',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 327,
                'permission_category_id'  => 24,
                'title'       => 'Create Notification',
                'slug'        => 'create-notification',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 328,
                'permission_category_id'  => 24,
                'title'       => 'Store Notification',
                'slug'        => 'store-notification',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 329,
                'permission_category_id'  => 24,
                'title'       => 'Edit Notification',
                'slug'        => 'edit-notification',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 330,
                'permission_category_id'  => 24,
                'title'       => 'Update Notification',
                'slug'        => 'update-notification',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 331,
                'permission_category_id'  => 24,
                'title'       => 'Show Notification',
                'slug'        => 'show-notification',
                'status'      => 1,
                'is_default'  => 1,
            ],
            [
                'id' => 332,
                'permission_category_id'  => 24,
                'title'       => 'Delete Notification',
                'slug'        => 'delete-notification',
                'status'      => 1,
                'is_default'  => 1,
            ],
        ]);
    }
}
