<?php

namespace App\Models\Admin\ServiceManagement;

use App\Models\Scopes\Searchable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class OurServiceCategory extends Model
{
    use HasFactory;
    use Searchable;

    protected $fillable = ['name', 'icon_class', 'description', 'status'];

    protected $searchableFields = ['*'];

    protected $table = 'our_service_categories';

    protected static $ourServiceCategory;

    protected static function boot()  // better use this method
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::deleting(function ($ourServiceCategory) {
            if (!empty($ourServiceCategory->ourServices))
            {
                $ourServiceCategory->ourServices->each->delete();
            }
        });
    }

    public static function createOrUpdateOurServiceCategory($request, $id = null)
    {
        if (isset($id))
        {
            self::$ourServiceCategory = OurServiceCategory::find($id);
        } else {
            self::$ourServiceCategory = new OurServiceCategory();
        }
        self::$ourServiceCategory->name               = $request->name;
        self::$ourServiceCategory->icon_class         = $request->icon_class;
        self::$ourServiceCategory->description        = $request->description;
        self::$ourServiceCategory->status             = $request->status == 'on' ? 1 : 0;
        self::$ourServiceCategory->save();
    }

    public static function deleteOurServiceCategory($id)
    {
        self::$ourServiceCategory = OurServiceCategory::find($id);
        self::$ourServiceCategory->delete();
    }

    public function ourServices()
    {
        return $this->hasMany(OurService::class);
    }
}
