<?php

namespace App\Models\Admin\BlogManagement;

use App\Models\Scopes\Searchable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class BlogCategory extends Model
{
    use HasFactory;
    use Searchable;

    protected $fillable = ['name', 'image', 'about', 'status'];

    protected $searchableFields = ['*'];

    protected $table = 'blog_categories';

    protected static $blogCategory;

    protected static function boot()  // better use this method
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::deleting(function ($blogCategory) {
            if (!empty($blogCategory->blogs))
            {
                $blogCategory->blogs->each->delete();
            }
        });
    }

    public static function createOrUpdateBlogCategory($request, $id = null)
    {
        if (isset($id))
        {
            self::$blogCategory = BlogCategory::find($id);
        } else {
            self::$blogCategory = new BlogCategory();
        }
        self::$blogCategory->name               = $request->name;
        self::$blogCategory->about              = $request->about;
        self::$blogCategory->image              = fileUpload($request->file('image'), 'blog_management/blog_categories', isset($id) ? static::find($id)->image : '');
        self::$blogCategory->status             = $request->status == 'on' ? 1 : 0;
        self::$blogCategory->save();
    }

    public static function deleteBlogCategory($id)
    {
        self::$blogCategory = BlogCategory::find($id);
        deleteFileFromServer(self::$blogCategory->image);
        self::$blogCategory->delete();
    }

    public function blogs()
    {
        return $this->hasMany(Blog::class);
    }
}
